### ISSUE TITLE
sapulatar-qt/main.py doesn't exist

### ISSUE THREAD

**Issue by zakaria-chahboun** [devlovers-id/sapulatar-qt#2]
I am using Linux, I have installed all dependencies, but when I start the application, it gives me:

> python3: can't open file '/home/zaki/.local/share/devlovers-id/sapulatar-qt/main.py': [Errno 2] No such file or directory

**Comment by raniaamina** [comment]
Hi, thanks for testing this tool.
We recently update the installation step in readme, would you try to check it please?

Shortly, just remove your last installation first.
Next, clone/download this repo, and then run `python3 setup install` form root repo directory.

Hope it help.

**Comment by raniaamina** [comment]
@zakaria-chahboun, Now sapulatar is ready to install via pip

https://pypi.org/project/sapulatar-qt/
